version: '3'

services:

  solr:
    image: solr
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=zoo:2181
    depends_on:
      - zoo
    command: solr-foreground

  zoo:
    tty: true
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
