version: '3'

services:

  solr:
    image: solr:8.11
    ports:
     - "8983:8983"
    volumes:
      - ./demo_public.der:/demo_public.der
    environment:
      - ZK_HOST=zoo:2181
    depends_on:
      - zoo
    command: "solr-fg -Denable.packages=true"

  zoo:
    tty: true
    image: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
