version: '3'

services:

  solr:
    image: solr:9.0
    ports:
     - "8983:8983"
    volumes:
      # enables the public key for loading plugins directly 
      # to be available in the solr container
      - ./demo_public.der:/demo_public.der
    # solr is run in cloud mode with packages turned on
    command: "solr-fg -c -Denable.packages=true"
